# WARNING - Generated by {fusen} from dev/flat_helpers.qmd: do not edit by hand

test_that("tally_delimited_string() works",
          {
            df <- data.frame(name = c("anna", "betty"),
              fruits = c("apple, banana", "pear, banana, banana"))
            
            expect_identical(tally_delimited_string(df, fruits),
                             structure(list(name = c("anna", "betty"),
                                            fruits_apple = c(TRUE, FALSE),
                                            fruits_banana = c(TRUE, TRUE),
                                            fruits_pear = c(FALSE, TRUE)),
                                       class = "data.frame",
                                       row.names = c(NA, -2L)))
          })
