# WARNING - Generated by {fusen} from dev/flat_helpers.qmd: do not edit by hand

test_that("range_labels() works",
          {
            expect_identical(
              
              range_labels(1:4, width = 2),
              
              ordered(c("1 — <3", "1 — <3", "3 — <5", "3 — <5"),
                      levels = c("1 — <3", "3 — <5")))
})

test_that("range_labels() can create all required levels",
          {
            expect_equal(
              levels(range_labels(c(1, 2.1), width = 1)),
              c("1 — <2", "2 — <3"))
          })

test_that("range_labels() crashes when it needs to",
          {
            expect_error(range_labels(1, start = 2, width = 1),
                         class = "start-too-high")
            
            expect_error(range_labels(1.2, width = 1, include = "integer"),
                         class = "non-integer-x")
          })

