# WARNING - Generated by {fusen} from dev/flat_colours-and-themes.qmd: do not edit by hand

#' Church Army Colours
#'
#' These functions each return the hexadecimal code of a colour in Church Army's brand
#'
#' These functions are wrappers around character vectors of length one. They take no arguments and always return the same string.
#'
#' @returns
#' A single character vector of length one.
#' @export
#' @rdname ca_cols
#' @examples
#' ca_purple()
ca_black <- function() "#000000"
#' @rdname ca_cols
#' @export
ca_white <- function() "#FFFFFF"
#' @rdname ca_cols
#' @export
ca_orange <- function() "#E84619"
#' @rdname ca_cols
#' @export
ca_gold   <- function() "#FBC900"
#' @rdname ca_cols
#' @export
ca_green  <- function() "#509E2F"
#' @rdname ca_cols
#' @export
ca_maroon <- function() "#910048"
#' @rdname ca_cols
#' @export
ca_cyan   <- function() "#0092BC"
#' @rdname ca_cols
#' @export
ca_purple <- function() "#523178"
#' @rdname ca_cols
#' @export
ca_light_teal <- function() "#6C8B93"
#' @rdname ca_cols
#' @export
ca_dark_teal  <- function() "#006272"
#' @rdname ca_cols
#' @export
ca_brown      <- function() "#6F2C3F"

#' Get a single church army colour by name
#'
#' A wrapper around \link[carutools]{ca_cols} that accepts one name and returns one colour
#'
#' @param x A character. Value must be one of \link[carutools]{ca_sample_cols}
#' @export
ca_col <- function(x){
  stopifnot(length(x) == 1)
  ca_cols(x)
}
