# WARNING - Generated by {fusen} from dev/flat_colours-and-themes.qmd: do not edit by hand

#' Get church army colours by name
#'
#' @param ... Any number of characters vectors. All values must all be in \link[carutools]{ca_sample_cols}
#' @returns A character vector
#' @export
#' @examples
#' ca_colours("cyan", "green", "purple")
#' ca_colour("darkteal")
#' ## colour names are forgiving:
#' ca_colour("dark-teal")
ca_colours <- function(...){
  
  x <- c(...)
  
  stopifnot(all(x %in% names(colours())))

  colours()[x]

}

#' Get single church army colour
#' 
#' @param x A string - must be one of \link[carutools]{ca_sample_cols}
#' @returns A single colour hexcode
#' @export
ca_colour <- function(x){
  stopifnot(is.character(x), length(x) == 1)

  ca_colours(x)
}

#' Vector of named Church Army colours
colours <- function(){
  c(
    black      = ca_black(),
    white      = ca_white(),
    orange     = ca_orange(),
    gold       = ca_gold(),
    green      = ca_green(),
    maroon     = ca_maroon(),
    cyan       = ca_cyan(),
    purple     = ca_purple(),
    
    lightteal    = ca_light_teal(),
    `light-teal` = ca_light_teal(),
    light_teal   = ca_light_teal(),
    
    darkteal    = ca_dark_teal(),
    `dark-teal` = ca_dark_teal(),
    dark_teal   = ca_dark_teal(),
    
    brown      = ca_brown())}
