# WARNING - Generated by {fusen} from dev/flat_colours-and-themes.qmd: do not edit by hand

# Palettes proper -------------------------------------------------------------
palettes <- list(
  orange      <- c("#E84619", "#ED6B47", "#F19074", "#F6B6A4", "#FADAD1"),
  gold       <- c("#FBC900", "#FCD446", "#FCDF74", "#FDE9A1", "#FEF4D0"),
  lightteal  <- c("#6C8B93", "#8AA2A9", "#A6B9BF", "#C4D1D3", "#E2E9E9"),
  light_teal  <- c("#6C8B93", "#8AA2A9", "#A6B9BF", "#C4D1D3", "#E2E9E9"),
  `light-teal`  <- c("#6C8B93", "#8AA2A9", "#A6B9BF", "#C4D1D3", "#E2E9E9"),
  cyan        <- c("#0092BC", "#36AFDA", "#68C4E2", "#9AD6EB", "#CCE9F3"),
  darkteal   <- c("#006272", "#35818D", "#67A1AB", "#9AC0C8", "#CCDFE3"),
  dark_teal   <- c("#006272", "#35818D", "#67A1AB", "#9AC0C8", "#CCDFE3"),
  `dark-teal`   <- c("#006272", "#35818D", "#67A1AB", "#9AC0C8", "#CCDFE3"),
  maroon      <- c("#9A054A", "#AE396F", "#C26A93", "#D89CBB", "#EBCED8"),
  purple      <- c("#523178", "#765B94", "#9784AE", "#BBAEC9", "#DCD6E4"),
  brown       <- c("#652430", "#85515A", "#A37C83", "#C1A7AD", "#E1D4D7"),
  green       <- c("#2AB04A", "#5EB66D", "#84C491", "#ACD6B5", "#D5E9D9")
)
# Palette functions --------------------------------------------------------------

#' Church Army Colour Pallets
#'
#' These functions each return a colour pallet from Church Army's brand
#'
#' These functions are wrappers around character vectors of length five.
#' They take no arguments and always return the same character vector.
#'
#' @returns
#' A single character vector of length five (nine in the case of `ca_pal_mix()`), containing colour hexcodes.
#' @rdname ca_pals
#' @export
ca_pal_orange     <- function() palettes$orange

#' @rdname ca_pals
#' @export
ca_pal_gold       <- function() palettes$gold

#' @rdname ca_pals
#' @export
ca_pal_light_teal <- function() palettes$light_teal

#' @rdname ca_pals
#' @export
ca_pal_cyan       <- function() palettes$cyan

#' @rdname ca_pals
#' @export
ca_pal_dark_teal  <- function() palettes$dark_teal

#' @rdname ca_pals
#' @export
ca_pal_maroon     <- function() palettes$maroon

#' @rdname ca_pals
#' @export
ca_pal_purple     <- function() palettes$purple

#' @rdname ca_pals
#' @export
ca_pal_brown      <- function() palettes$brown

#' @rdname ca_pals
#' @export
ca_pal_green      <- function() palettes$green

#' @rdname ca_pals
#' @export
ca_pal_mix <- function(){
  out <- c(ca_gold(), ca_cyan(), ca_green(), ca_purple(),
           ca_light_teal(), ca_orange(), ca_brown(),
           ca_dark_teal(), ca_maroon())
  out
}

get_pal <- function(x) palettes[[x]]

## Get ca_pal_* by name

#' See all Church Army palette and colour names
#'
#' A character vector of colour or pallette names accepted by `carutools` functions. For instance,
#' \link[carutools]{ca_pal} will only accept a name from `ca_sample_pals()`.
#'
#' @returns A character vector of Church Army palette or colour names
#' @export
ca_sample_pals    <- function(){
  c("mix", "orange", "gold", "light-teal", "cyan", "dark-teal", "purple", "brown", "green")
}

#' @export
#' @rdname ca_sample_pals
ca_sample_cols <- function() return(names(colours))

#' Get a church army palette by name
#'
#' This function returns a Church Army palette specified by the user
#'
#' Depending on which of the names in `get_pal()` is passed to `which_pal`,
#' the hexcodes of one of Church Army's colour palettes is returned
#'
#' `which_pal` must exactly match one of `ca_sample_pals()`, otherwise an error is thrown.
#'
#' @returns
#' A character vector of length 5
#'
#' @param which_pal A character, which must be one of \link[carutools]{ca_sample_pals}.
#' @export
ca_pal <- function(which_pal = NULL){

  stopifnot(length(which_pal) == 1)

  if(is.null(which_pal) || !which_pal %in% ca_sample_pals()){
    rlang::abort("You must specify a pallet name. See ca_sample_pals() for all valid palettes")
  }
  get_pal(which_pal)
}
