# WARNING - Generated by {fusen} from dev/flat_helpers.qmd: do not edit by hand

#' Range labels
#'
#' Create 'range labels' for grouping and tabulating a continuous variable
#'
#' @returns
#' A character vector of labels
#' @param x a numeric vector
#' @param width Desidered label width - numeric
#' @param start The number from which to start the lowest range label
#' @param include Which side of each range should be included. One of 'upper', 'lower' or 'integer' - the latter is a special case that deals exclusively with integer ranges and otherwise crashes.
#' @param sep The character used to separate values within each label
#' @param explicit_zero Logical; should zeroes have a label all to themselves? They do by default.
#' @param suffix Optional suffix to append to each label (e.g. "%")
#' @param ordered Logical; should output be an ordered factor?
#' @export
#' 
#' @examples
#' range_labels(1:10, width = 3)
#' range_labels(1:10, width = 3, include = "lower", start = 0, explicit_zero = TRUE)
range_labels <- function(x, width, start = NA,
                         sep = " — ", explicit_zero = TRUE, suffix = "",
                         include = c("upper", "lower", "integer"),
                         ordered = TRUE){
  
  include <- match.arg(include)
  if(include == "integer" && any(x %% 1 != 0)) rlang::abort("'include = integer' can only be used with an all-integer x",
                                                     class = "non-integer-x")
  
  if(is.na(start)) start <- min(x)
  if(start > min(x)) rlang::abort("'start' cannot be higher than the lowest value in 'x'",
                                  class = "start-too-high")
  
  ## Adjust rounding function depending on whether upper or lower boundaries
  ## are to be included in each level
  if(include %in% c("lower", "integer")) level_round <- ceiling
  else level_round <- floor
  
  make_levels <- \(y){
    ## Assume start from zero
    levs <- level_round((y - start) / width) + 1
    levs
  }
    
  make_labels <- \(y){
    
    vals <- (y - 1) * width + start

    if(include == "upper"){
      labs <- paste(vals, paste0("<", vals + width), sep = sep)
    } else if(include == "lower") {
      labs <- paste(paste0(">", vals - width), vals, sep = sep)
    } else if(include == "integer"){
      labs <- paste(vals - width + 1, vals, sep = sep)
    }

    if(explicit_zero) labs[y == 0] <- "0"
    paste0(labs, suffix)
  }

  levels <- make_levels(x)
  labels <- make_labels(levels)

  if(ordered){
    
    complete_levels <- make_levels(start):make_levels(max(x))
    complete_labels <- make_labels(complete_levels)

    labels <- ordered(labels, levels = unique(complete_labels))
  }

  labels

}

