# WARNING - Generated by {fusen} from dev/flat_helpers.qmd: do not edit by hand

#' Relabeller
#'
#' A function factory that constructs a \link[dplyr]{case_match} function. Useful for the `labels` argument of ggplot's `scale_*_*` functions.
#'
#' @param ... Any number of formulae in the format `'old_label' ~ 'new_label'`.
#' @returns
#' A relabelling function
#' @export
#' @examples
#' fruits <- c("apple", "pear", "pear", "banana")
#'
#' fruit_relabel <- relabeller("pear" ~ "orange", "banana" ~ "plum")
#' fruit_relabel(fruits)
#'
#' ## Normal use case
#' \dontrun{
#' ggplot(palmerpenguins::penguins, aes(x = sex, y = flipper_length_mm)) +
#'   geom_point(alpha = 0.5) +
#'   scale_x_discrete(labels = relabeller("male" ~ "BOY\nPENGUIN", "female" ~ "GIRL\nPENGUIN"))
#' }

relabeller <- function(...){

  dots <- rlang::enexprs(...)

  rlang::new_function(
    args = rlang::pairlist2(x =),
    body = rlang::expr({
      dplyr::case_match(
        x,
        !!!dots,
        .default = x
      )}
    ))}

